name: libwebsockets Tests

# START OF COMMON SECTION
on:
  push:
    branches: [ '*' ]     # [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  build_wolfprovider:
    uses: ./.github/workflows/build-wolfprovider.yml
    with:
      wolfssl_ref: ${{ matrix.wolfssl_ref }}
      openssl_ref: ${{ matrix.openssl_ref }}
      replace_default: ${{ matrix.replace_default }}
    strategy:
      matrix:
        wolfssl_ref: [ 'v5.8.2-stable' ]
        openssl_ref: [ 'openssl-3.5.2' ]
        replace_default: [ true ]

  test_libwebsockets:
    runs-on: ubuntu-22.04
    container:
      image: debian:bookworm
      env:
        DEBIAN_FRONTEND: noninteractive
    needs: build_wolfprovider
    # This should be a safe limit for the tests to run.
    timeout-minutes: 20
    strategy:
      matrix:
        libwebsockets_ref: [ 'main', 'v4.3.3' ]
        wolfssl_ref: [ 'v5.8.2-stable' ]
        openssl_ref: [ 'openssl-3.5.2' ]
        replace_default: [ true ]
        force_fail: [ 'WOLFPROV_FORCE_FAIL=1', '' ]
        exclude:
          - libwebsockets_ref: 'main'
            force_fail: 'WOLFPROV_FORCE_FAIL=1'
    env:
      WOLFSSL_PACKAGES_PATH: /tmp/wolfssl-packages
      OPENSSL_PACKAGES_PATH: /tmp/openssl-packages
      WOLFPROV_PACKAGES_PATH: /tmp/wolfprov-packages
    steps:
      # Checkout the source so we can run the check-workflow-result script
      - name: Checkout wolfProvider
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Checking OpenSSL/wolfProvider packages in cache
        uses: actions/cache/restore@v4
        id: wolfprov-cache-restore
        with:
          path: |
            ${{ env.WOLFSSL_PACKAGES_PATH }}
            ${{ env.OPENSSL_PACKAGES_PATH }}
            ${{ env.WOLFPROV_PACKAGES_PATH }}
          key: openssl-wolfprov-debian-packages-${{ github.sha }}${{ matrix.replace_default && '-replace-default' || '' }}
          fail-on-cache-miss: true

      - name: Install wolfSSL/OpenSSL/wolfprov packages
        run: |
          printf "Installing OpenSSL/wolfProvider packages:\n"
          ls -la ${{ env.WOLFSSL_PACKAGES_PATH }}
          ls -la ${{ env.OPENSSL_PACKAGES_PATH }}
          ls -la ${{ env.WOLFPROV_PACKAGES_PATH }}
          apt install --reinstall -y \
            ${{ env.WOLFSSL_PACKAGES_PATH }}/libwolfssl_*.deb
          apt install --reinstall -y \
            ${{ env.OPENSSL_PACKAGES_PATH }}/openssl_*.deb \
            ${{ env.OPENSSL_PACKAGES_PATH }}/libssl3_*.deb \
            ${{ env.OPENSSL_PACKAGES_PATH }}/libssl-dev_*.deb
          apt install --reinstall -y \
            ${{ env.WOLFPROV_PACKAGES_PATH }}/libwolfprov_*.deb

      - name: Install libwebsockets dependencies
        run: |
          apt-get update
          apt-get install -y libc6 libcap2 zlib1g cmake build-essential

      - name: Download libwebsockets
        uses: actions/checkout@v4
        with:
          repository: warmcat/libwebsockets
          ref: ${{ matrix.libwebsockets_ref }}
          path: libwebsockets

      # Generate test certificates before building
      - name: Generate test certificates
        working-directory: libwebsockets
        run: |
          mkdir -p build
          cd build
          openssl req -x509 -newkey rsa:2048 -keyout libwebsockets-test-server.key.pem -out libwebsockets-test-server.pem -days 365 -nodes -subj "/CN=localhost"

      - name: Build libwebsockets
        working-directory: libwebsockets
        run: |
          cd build
          cmake .. -DLWS_WITH_SSL=ON -DLWS_OPENSSL_LIBRARIES=/usr/lib/x86_64-linux-gnu/libssl.so -DLWS_OPENSSL_INCLUDE_DIRS=/usr/include/openssl
          make -j$(nproc)
          # Skip make install to avoid certificate installation issues
          # make install

      # Set up wolfProvider environment before running tests
      - name: Setup wolfProvider environment
        run: |
          if [ -f $GITHUB_WORKSPACE/scripts/env-setup ]; then
            source $GITHUB_WORKSPACE/scripts/env-setup
          fi
          # Alternative: Set up environment variables manually if env-setup script doesn't exist
          export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
          export OPENSSL_CONF=/etc/ssl/openssl.cnf

      - name: Run libwebsockets tests
        working-directory: libwebsockets
        shell: bash
        run: |
          # Set up wolfProvider environment
          if [ -f $GITHUB_WORKSPACE/scripts/env-setup ]; then
            source $GITHUB_WORKSPACE/scripts/env-setup
          fi
          export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"

          export ${{ matrix.force_fail }}
          ./build/bin/libwebsockets-test-server --port=11111 --ssl > server.log 2>&1 & SERVER_PID=$!
          sleep 5
          timeout 10 ./build/bin/libwebsockets-test-client 127.0.0.1 --port=11111 --ssl > client.log 2>&1 || echo "Client exited with error $?"
          ldd ./build/bin/libwebsockets-test-server | grep wolfProvider || echo "wolfProvider not found in server"
          ldd ./build/bin/libwebsockets-test-client | grep wolfProvider || echo "wolfProvider not found in client"
          kill $SERVER_PID || echo "Server already exited"
          cat server.log || echo "Missing server.log"
          cat client.log || echo "Missing client.log"
          cat server.log client.log > libwebsockets-test.log
          if grep -q "error:03080006" libwebsockets-test.log || grep -q "Failed to create default vhost" libwebsockets-test.log; then
            TEST_RESULT=1
          else
            TEST_RESULT=0
          fi
          $GITHUB_WORKSPACE/.github/scripts/check-workflow-result.sh $TEST_RESULT ${{ matrix.force_fail }} libwebsockets
